---
- name: Converge
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Apply ssh_transfer_key role
      ansible.builtin.include_role:
        name: marcus_grant.dotfiles.ssh_transfer_key
      vars:
        ssh_transfer_key_owner: testuser
        ssh_transfer_key_pairs:
          - src: /tmp/molecule-ssh-keys/id_test_full
            name: id_test_full
          - src: /tmp/molecule-ssh-keys/id_test_nopub
            name: id_test_nopub
