---
- name: Converge
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Apply ssh_config role
      ansible.builtin.include_role:
        name: marcus_grant.dotfiles.ssh_config
      vars:
        ssh_config_owner: testuser
        ssh_config_common_entries:
          - host: github.com
            user: git
            identity_file: ~/.ssh/id_ed25519_git
        ssh_config_host_entries:
          - host: myserver
            host_name: 192.168.1.10
            user: marcus
            port: 2222
            identity_file: ~/.ssh/id_ed25519_personal
            ssh_authorize: true
            home: /tmp/some-path
        ssh_config_defaults:
          add_keys_to_agent: "yes"
          identities_only: "yes"
        ssh_config_controller_kh_path: /tmp/molecule_kh_fixture
