---
- name: Converge
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Apply pip role
      ansible.builtin.include_role:
        name: marcus_grant.dotfiles.pip
      vars:
        pip_owner: testuser
        pip_packages:
          - httpie
