# SPDX-License-Identifier: GPL-3.0-only
---
# tasks file for nvm

- name: Update package cache
  ansible.builtin.package:
    update_cache: true
  changed_when: false

- name: Install git for NVM installation
  ansible.builtin.package:
    name: git
    state: present

- name: Set NVM installation directory
  ansible.builtin.set_fact:
    _nvm_dir: >-
      {%- if nvm_dir -%}
        {{ nvm_dir }}
      {%- elif nvm_xdg_compliant and ansible_env.XDG_DATA_HOME is defined -%}
        {{ ansible_env.XDG_DATA_HOME }}/nvm
      {%- else -%}
        {{ ansible_env.HOME }}/.nvm
      {%- endif -%}

- name: Set NVM cache directory
  ansible.builtin.set_fact:
    _nvm_cache_dir: >-
      {%- if nvm_cache_dir -%}
        {{ nvm_cache_dir }}
      {%- elif nvm_xdg_compliant and ansible_env.XDG_CACHE_HOME is defined -%}
        {{ ansible_env.XDG_CACHE_HOME }}/nvm
      {%- else -%}
        {{ ansible_env.HOME }}/.cache/nvm
      {%- endif -%}

- name: Set NVM node prefix directory
  ansible.builtin.set_fact:
    _nvm_node_prefix: >-
      {%- if nvm_node_prefix -%}
        {{ nvm_node_prefix }}
      {%- elif nvm_xdg_compliant and ansible_env.XDG_DATA_HOME is defined -%}
        {{ ansible_env.XDG_DATA_HOME }}/nvm/versions
      {%- else -%}
        {{ _nvm_dir }}/versions
      {%- endif -%}

- name: Set NVM npm config prefix directory
  ansible.builtin.set_fact:
    _nvm_npm_config_prefix: >-
      {%- if nvm_npm_config_prefix -%}
        {{ nvm_npm_config_prefix }}
      {%- elif nvm_xdg_compliant and ansible_env.XDG_DATA_HOME is defined -%}
        {{ ansible_env.XDG_DATA_HOME }}/npm
      {%- else -%}
        {{ ansible_env.HOME }}/.npm-global
      {%- endif -%}

- name: Clone NVM repository
  ansible.builtin.git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "{{ _nvm_dir }}"
    version: "{{ nvm_version }}"
    recursive: false
