#SPDX-License-Identifier: MIT-0
---
# tasks file for nodejs

- name: Update package cache
  ansible.builtin.package:
    update_cache: true
  become: true

- name: Install nodejs and npm
  ansible.builtin.package:
    name:
      - nodejs
      - npm
    state: present
  become: true
