---
- name: Converge
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Apply neovim role
      ansible.builtin.include_role:
        name: marcus_grant.dotfiles.neovim
      vars:
        neovim_owner: testuser
        neovim_install_method: package
        neovim_git_repo: /opt/test-dots-nvim
        neovim_git_version: main
