FROM archlinux:latest

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm systemd python sudo && \
    systemctl enable systemd-resolved && \
    systemctl enable systemd-networkd

RUN echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

VOLUME ["/sys/fs/cgroup"]
CMD ["/usr/lib/systemd/systemd"]
