---
- name: Converge
  hosts: all
  vars:
    profile_user: root
    profile_group: root
  tasks:
    - name: Apply profile role
      ansible.builtin.include_role:
        name: marcus_grant.dotfiles.profile

    - name: Apply zsh role
      ansible.builtin.include_role:
        name: marcus_grant.dotfiles.zsh
      vars:
        zsh_git_repo: /opt/test-dots-zsh
        zsh_shell_as_default: true
        zsh_git_force: true
