---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian12
    image: geerlingguy/docker-debian12-ansible
    pre_build_image: true
  - name: debian-sid
    image: debian:sid
    dockerfile: Dockerfile-debian-sid.j2
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    command: /usr/lib/systemd/systemd
  - name: fedora
    image: geerlingguy/docker-fedora39-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
