---
- name: Converge
  hosts: all
  vars:
    profile_user: root
    profile_group: root
  tasks:
    - name: Run profile role first
      ansible.builtin.include_role:
        name: marcus_grant.dotfiles.profile

    - name: Run userdirs role
      ansible.builtin.include_role:
        name: marcus_grant.dotfiles.userdirs
      vars:
        userdirs_custom_dirs:
          - "{{ ansible_env.HOME }}/testdir"
