# SPDX-License-Identifier: GPL-3.0-only
galaxy_info:
  author: marcus-grant
  description: System-level installation of Node.js and npm with optional global packages
  company: ""

  license: GPL-3.0-only

  min_ansible_version: "2.15"

  platforms:
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - nodejs
    - npm
    - javascript
    - development

collections:
  - community.general

dependencies: []
