---
galaxy_info:
  role_name: ssh_config
  namespace: marcus_grant
  author: marcus_grant
  description: |
    Template ~/.ssh/config from lists of host entries. Manages .ssh directory
    permissions and optional known_hosts static entries.
  issue_tracker_url: https://github.com/marcus-grant/ansible-collection-dotfiles/issues
  license: GPL-2.0-or-later
  min_ansible_version: '2.1'
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: Archlinux
      versions:
        - all
  galaxy_tags:
    - dotfiles
    - ssh
    - config
    - security

dependencies: []
