---
galaxy_info:
  role_name: git
  author: marcus_grant
  description: Install git and configure global git settings for a specified user.
  issue_tracker_url: https://github.com/marcus-grant/ansible-collection-dotfiles/issues
  license: GPL-2.0-or-later

  min_ansible_version: '2.1'

  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: Archlinux
      versions:
        - all

  galaxy_tags:
    - dotfiles
    - dots
    - git
    - config
    - shell

dependencies: []
